version: '2'

services:

  templates:
    image: portainer/templates
    container_name: "portainer-templates"
    networks:
      - local

  portainer:
    image: portainer/portainer
    container_name: "portainer-app"
#Automatically choose 'Manage the Docker instance where Portainer is running' by adding <--host=unix:///var/run/docker.sock> to the command
    command: --templates http://templates/templates.json
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - c:/docker/data/portainer:/data
    ports:
      - "9000:9000"

  watchtower:
    image: v2tec/watchtower
    container_name: "portainer-watchtower"
    command: --cleanup portainer-app portainer-watchtower portainer/templates
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  sonarr:
    image: linuxserver/sonarr
    container_name: "sonarr"
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - c:/docker/data/sonarr:/config
      - storage:/tv
    ports:
      - "8989:8989"
    environment:
      - TZ=America/Los_Angeles
      
      
  jackett:
    image: linuxserver/jackett
    container_name: "jackett"
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - c:/docker/data/jackett:/config
    ports:
      - "9117:9117"
    environment:
      - TZ=America/Los_Angeles
      
  radarr:
    image: linuxserver/radarr
    container_name: "radarr"
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - c:/docker/data/radarr:/config
      - storage:/movies
    ports:
      - "7878:7878"
    environment:
      - TZ=America/Los_Angeles

networks:
  local:
    driver: bridge
    
volumes:
  storage:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NASName},nolock,soft,rw"
      device: ":${NASShare}"